Repository AI-News-Team/AI-News, pull requests merged in 2023-08, with the labels that each got.

#79 Scrape and Paraphrase daily
  .gitattributes
  api/route/Article/article.create_raw.ts
  docker-compose.yml
  reWriter/Dockerfile
  reWriter/reWriter.cron.sh
  scraper/Dockerfile
  scraper/scrape.cron.sh
Labels: Feature, Web Scraping, Paraphraser, Containerization

#86 84 improve semantic search
  api/route/Article/article.create_raw.ts
  api/route/Article/article.search.domain.ts
  database/src/init.sql
  reWriter/reWriter.py
  scraper/newsscrapper/pipelines.py
  scraper/requirements.txt
  search/main.py
Labels: Web Scraping, API, Database, Semantic Search

#99 Gseal 83 scraping links in article body
  scraper/newsscrapper/spiders/bbc.py
  scraper/newsscrapper/spiders/cnn.py
  scraper/newsscrapper/spiders/foxNews.py
  scraper/newsscrapper/spiders/newYorkTimes.py
Labels: Bug, Web Scraping

#89 Gseal 74 rewrite story titles
  api/route/Article/article.create.ts
  api/route/Article/article.get.ts
  api/route/Article/article.getAll.ts
  api/route/Article/article.summary.ts
  client/src/pages/ArticlePage.tsx
  client/src/styles/colors.tsx
  database/src/init.sql
  reWriter/reWriter.py
Labels: Bug, Paraphraser, Front End
